package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "20-blanks",
		Description: "Deck of 20 blank response cards",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `Ain't it nifty? Barb and Bob hit 50! So get off your ass and raise a glass to 50 years of %s.`},
			&PromptCard{Prompt: `Duuuuuuude. You have got to go to space. %s is awesome in space.`},
			&PromptCard{Prompt: `Five, four, three, two, one… %s!`},
			&PromptCard{Prompt: `For hunting in the King's forest, I hereby sentence you to death by %s.`},
			&PromptCard{Prompt: `Give me ten good men and 48 hours. I'll get you %s.`},
			&PromptCard{Prompt: `Goldfinger! / He's the man, / the man with %s.`},
			&PromptCard{Prompt: `Goodbye, %s, hello %s!`},
			&PromptCard{Prompt: `Here's a little something I learned in business school: The customer is always %s.`},
			&PromptCard{Prompt: `Hey, honey. For the bedroom, were you thinking, ""Robin's Egg Blue"" or %sPink?""`},
			&PromptCard{Prompt: `I hate this job. I hate this place. Most of all, I hate %s. I quit.`},
			&PromptCard{Prompt: `I have solved politics. My solution is %s.`},
			&PromptCard{Prompt: `I so drunk I %s.`},
			&PromptCard{Prompt: `I swear to God I'm gonna murder my husband if he doesn't shut the fuck up about %s.`},
			&PromptCard{Prompt: `In bookstores now: "From %s to %s: A memoir."`},
			&PromptCard{Prompt: `In Radiohead's new single, Thom Yorke repeats the phrase "%s" dozens of times over a skittering drum beat.`},
			&PromptCard{Prompt: `It's finally happening! I'm finally doing it! Yes! It's time for %s!`},
			&PromptCard{Prompt: `It's late at night. You're in bed with your lover, Patrick Stewart. He leans over with a twinkle in his eye and asks "How about %s?"`},
			&PromptCard{Prompt: `It's the 21st century. A woman shouldn't have to apologize for %s.`},
			&PromptCard{Prompt: `Ladies and gentlemen, I propose a two-pronged plan. The first prong will be %s, and the second prong will be %s.`},
			&PromptCard{Prompt: `Live from Universal Studios, it's America's favorite game show! "%s or %s?"`},
			&PromptCard{Prompt: `Millions of copies sold! Donald Trump's "The Art of %s."`},
			&PromptCard{Prompt: `New at TGI Fridays! It's what you've been waiting for: The %s Burger.`},
			&PromptCard{Prompt: `Oh no! Here it comes! Ohhhhh god! It's %s.`},
			&PromptCard{Prompt: `Oh you haaaaaaave to see this new documentary on Netflix. I don't want to give anything away, but let's just say it will change the way you look at %s.`},
			&PromptCard{Prompt: `Oh, the weather outside is frightful. But %s is so delightful.`},
			&PromptCard{Prompt: `One, two, three and to the four, Snoop Doggy Dogg and Dr. Dre is %s.`},
			&PromptCard{Prompt: `Personal foul: %s. 15-yard penalty. Automatic first down.`},
			&PromptCard{Prompt: `Rub a dub dub, %s in a tub!`},
			&PromptCard{Prompt: `Say it loud! I'm %s and I'm proud!`},
			&PromptCard{Prompt: `Seriously guys, there's nothing funny about %s.`},
			&PromptCard{Prompt: `Sweetheart, you and your sister escel in different ways. She's got her violin, and you've got %s.`},
			&PromptCard{Prompt: `That's bullshit! They can't fire me for %s!`},
			&PromptCard{Prompt: `The sequel is here! Get Ready for %s2: %s.`},
			&PromptCard{Prompt: `Times have changed, girlfriend. If you want to meet people in New York, you got to be down for %s.`},
			&PromptCard{Prompt: `Unfortunately, no one can be told what %s is. You have to experience it for yourself.`},
			&PromptCard{Prompt: `What has my life become? I'm jerking off to a video called "co-ed absolutely destroyed by %s."`},
			&PromptCard{Prompt: `What sounds great after four margaritas? %s`},
			&PromptCard{Prompt: `What's hot, smelly, and about to die? %s`},
			&PromptCard{Prompt: `What's secretly a Russian plot to destabilize the West? %s`},
			&PromptCard{Prompt: `What's up, YouTube? User DanTheMan wanted to see %s, so here we go.`},
			&PromptCard{Prompt: `Why did the chicken cross the road? %s`},
			&PromptCard{Prompt: `Why my mustache smell so bad? %s`},
			&PromptCard{Prompt: `Yeah that's so hot. I'm so close. Talk about %s again! OH I'M CUMMING!`},
			&PromptCard{Prompt: `You can call me David Copperfield, because I'm about to make %s disappear.`},
			&PromptCard{Prompt: `You city folk would never understand the quiet dignity of %s.`},
		},
		Responses: []ResponseCard{
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
		},
	}

	AddPack(pack)
}
