package cardsagainstdiscord

func init() {
	pack := &CardPack{
		Name:        "blanks",
		Description: "Deck of 60 blank response cards",
		Prompts: []*PromptCard{
			&PromptCard{Prompt: `%s + %s = %s.`},
			&PromptCard{Prompt: `%s is a slippery slope that leads to %s.`},
			&PromptCard{Prompt: `%s would be woefully incomplete without %s.`},
			&PromptCard{Prompt: `%s: good to the last drop.`},
			&PromptCard{Prompt: `%s: kid-tested, mother-approved.`},
			&PromptCard{Prompt: `%s: Once you pop, the fun don't stop!`},
			&PromptCard{Prompt: `%s? Jim'll fix it!`},
			&PromptCard{Prompt: `%s? There's an app for that.`},
			&PromptCard{Prompt: `%s? Yeah, nah.`},
			&PromptCard{Prompt: `%s. Awesome in theory, kind of a mess in practice.`},
			&PromptCard{Prompt: `%s. Betcha can't have just one!`},
			&PromptCard{Prompt: `%s. High five, bro.`},
			&PromptCard{Prompt: `%s. It's a trap!`},
			&PromptCard{Prompt: `%s. That was so metal.`},
			&PromptCard{Prompt: `%s. That's how I want to die.`},
			&PromptCard{Prompt: `%s. That's why mums go to Iceland.`},
			&PromptCard{Prompt: `★✰✰✰✰ Do NOT go here! Found %s in my Kung Pao chicken! `},
			&PromptCard{Prompt: `50%% of all marriages end in %s.`},
			&PromptCard{Prompt: `A recent laboratory study shows that undergraduates have 50%% less sex after being exposed to %s.`},
			&PromptCard{Prompt: `A remarkable new study has shown that chimps have evolved their own primitive version of %s.`},
			&PromptCard{Prompt: `A romantic, candlelit dinner would be incomplete without %s.`},
			&PromptCard{Prompt: `A successful job interview begins with a firm handshake and ends with %s.`},
			&PromptCard{Prompt: `ABC presents: "%s: The Story of %s."`},
			&PromptCard{Prompt: `After eight years in the White House, how is Obama finally letting loose? %s`},
			&PromptCard{Prompt: `After four platinum albums and three Grammys, it's time to get back to my roots, to what inspired me to make music in the first place: %s.`},
			&PromptCard{Prompt: `After Hurricane Katrina, Sean Penn brought %s to all the people of New Orleans.`},
			&PromptCard{Prompt: `After months of practice with %s, I think I’m finally ready for %s.`},
			&PromptCard{Prompt: `After the earthquake, Sean Penn brought %s to the people of Haiti.`},
			&PromptCard{Prompt: `Air Canada guidelines now prohibit %s on airplanes.`},
			&PromptCard{Prompt: `Airport security guidelines now prohibit %s on airplanes.`},
			&PromptCard{Prompt: `Alternative medicine is now embracing the curative powers of %s.`},
			&PromptCard{Prompt: `And the Academy Award for %s goes to %s.`},
			&PromptCard{Prompt: `And the BAFTA for %s goes to %s. `},
			&PromptCard{Prompt: `And what did you bring for show and tell? %s`},
			&PromptCard{Prompt: `Anthropologists have recently discovered a primitive tribe that worships %s.`},
			&PromptCard{Prompt: `Arby's: We Have %s.`},
			&PromptCard{Prompt: `"Are you thinking what I'm thinking, B1? I think I am, B2: it's %s time!"`},
			&PromptCard{Prompt: `As my New Year's resolution, I vow to give up %s.`},
			&PromptCard{Prompt: `As the mum of five rambunctious boys, I'm no stranger to %s.`},
			&PromptCard{Prompt: `Betcha can't have just one! %s`},
			&PromptCard{Prompt: `BILLY MAYS HERE FOR %s.`},
			&PromptCard{Prompt: `Bravo's new reality show features eight washed-up celebrities living with %s.`},
			&PromptCard{Prompt: `Brought to you by Bud Light®, the Official Beer of %s.`},
			&PromptCard{Prompt: `But before I kill you, Mr. Bond, I must show you %s.`},
			&PromptCard{Prompt: `CBC presents "%s: the Story of %s."`},
			&PromptCard{Prompt: `Channel 4 presents %s, the story of %s.`},
			&PromptCard{Prompt: `Channel 5's new reality show features eight washed-up celebrities living with %s.`},
			&PromptCard{Prompt: `Channel 9 is pleased to present its new variety show, "Hey Hey It's %s."`},
			&PromptCard{Prompt: `Charades was ruined for me forever when my mom had to act out %s.`},
			&PromptCard{Prompt: `Check me out, yo! I call this dance move "%s."`},
			&PromptCard{Prompt: `Click Here for %s!!!`},
			&PromptCard{Prompt: `Coming this season, Samuel Beckett's classic existential play: Waiting for %s.`},
			&PromptCard{Prompt: `Coming to Broadway this season, %s: The Musical.`},
			&PromptCard{Prompt: `Crikey! I've never seen %s like this before! Let's get a bit closer.`},
			&PromptCard{Prompt: `CTV presents "%s: the Story of %s."`},
			&PromptCard{Prompt: `Daddy, why is mummy crying? %s`},
			&PromptCard{Prompt: `Dear Abby, I'm having some trouble with %s and would like your advice.`},
			&PromptCard{Prompt: `Dear Agony Aunt, I'm having some trouble with %s and I need your advice.`},
			&PromptCard{Prompt: `Dear Sir or Madam, We regret to inform you that the Office of %s has denied your request for %s.`},
			&PromptCard{Prompt: `Doctor, you've gone too far! The human body wasn't meant to withstand that amount of %s!`},
			&PromptCard{Prompt: `Dude, do not go in that bathroom. There's %s in there.`},
			&PromptCard{Prompt: `Due to a PR fiasco, Walmart no longer offers %s.`},
			&PromptCard{Prompt: `During his childhood, Salvador Dali produced hundreds of paintings of %s.`},
			&PromptCard{Prompt: `During his midlife crisis, my dad got really into %s.`},
			&PromptCard{Prompt: `During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of %s.`},
			&PromptCard{Prompt: `During sex, I like to think about %s.`},
			&PromptCard{Prompt: `Finally! A service that delivers %s right to your door.`},
			&PromptCard{Prompt: `For my next trick, I will pull %s out of %s.`},
			&PromptCard{Prompt: `Fun tip! When your man asks you to go down on him, try surprising him with %s instead.`},
			&PromptCard{Prompt: `Future historians will agree that %s marked the beginning of America's decline.`},
			&PromptCard{Prompt: `Having problems with %s? Try %s!`},
			&PromptCard{Prompt: `"Here is the church, Here is the steeple, Open the doors and there is %s."`},
			&PromptCard{Prompt: `Hey guys, welcome to TGIF! Would you like to start the night off right with %s?`},
			&PromptCard{Prompt: `Hey Reddit! I'm %s. Ask me anything.`},
			&PromptCard{Prompt: `How am I maintaining my relationship status? %s`},
			&PromptCard{Prompt: `How did I lose my virginity? %s`},
			&PromptCard{Prompt: `I do not know with what weapons World War III will be fought, but World War IV will be fought with %s.`},
			&PromptCard{Prompt: `I drink to forget %s.`},
			&PromptCard{Prompt: `I get by with a little help from %s.`},
			&PromptCard{Prompt: `I got 99 problems but %s ain't one.`},
			&PromptCard{Prompt: `I know when that hotline bling, that can only mean one thing: %s.`},
			&PromptCard{Prompt: `I learned the hard way that you can't cheer up a grieving friend with %s.`},
			&PromptCard{Prompt: `I never truly understood %s until I encountered %s.`},
			&PromptCard{Prompt: `I spent my whole life working toward %s, only to have it ruined by %s.`},
			&PromptCard{Prompt: `I wish I hadn't lost the instruction manual for %s.`},
			&PromptCard{Prompt: `I'm going on a cleanse this week. Nothing but kale juice and %s.`},
			&PromptCard{Prompt: `I'm Lebron James, and when I'm not slamming dunks, I love %s.`},
			&PromptCard{Prompt: `I'm no doctor, but I'm pretty sure what you're suffering from is called "%s."`},
			&PromptCard{Prompt: `I'm sorry, Professor, but I couldn't complete my homework because of %s.`},
			&PromptCard{Prompt: `I'm sorry, Sir, but I couldn't complete my homework because of %s.`},
			&PromptCard{Prompt: `I’m not like the rest of you. I’m too rich and busy for %s.`},
			&PromptCard{Prompt: `If you can't be with the one you love, love %s.`},
			&PromptCard{Prompt: `IF you like %s, YOU MIGHT BE A REDNECK.`},
			&PromptCard{Prompt: `In 1,000 years, when paper money is but a distant memory, %s will be our currency.`},
			&PromptCard{Prompt: `In a world ravaged by %s, our only solace is %s.`},
			&PromptCard{Prompt: `In Australia, %s is twice as big and twice as deadly.`},
			&PromptCard{Prompt: `In Belmarsh Prison, word is you can trade 200 cigarettes for %s.`},
			&PromptCard{Prompt: `In her latest feature-length film, Tracy Beaker struggles with %s for the first time.`},
			&PromptCard{Prompt: `In his new self-produced album, Kanye West raps over the sounds of %s.`},
			&PromptCard{Prompt: `In his new summer comedy, Rob Schneider is %s trapped in the body of %s.`},
			&PromptCard{Prompt: `In L.A. County Jail, word is you can trade 200 cigarettes for %s.`},
			&PromptCard{Prompt: `In M. Night Shyamalan's new movie, Bruce Willis discovers that %s had really been %s all along.`},
			&PromptCard{Prompt: `In Michael Jackson's final moments, he thought about %s.`},
			&PromptCard{Prompt: `In Rome, there are whisperings that the Vatican has a secret room devoted to %s.`},
			&PromptCard{Prompt: `In the new Disney Channel Original Movie, Hannah Montana struggles with %s for the first time.`},
			&PromptCard{Prompt: `In the seventh circle of Hell, sinners must endure %s for all eternity.`},
			&PromptCard{Prompt: `In Wormwood Scrubs, word is you can trade 200 cigarettes for %s.`},
			&PromptCard{Prompt: `Instead of coal, Santa now gives the bad children %s.`},
			&PromptCard{Prompt: `Introducing the amazing superhero/sidekick duo! It's %s and %s!`},
			&PromptCard{Prompt: `Introducing X-Treme Baseball! It's like baseball, but with %s!`},
			&PromptCard{Prompt: `It's a trap!`},
			&PromptCard{Prompt: `It’s a pity that kids these days are all getting involved with %s.`},
			&PromptCard{Prompt: `Just once, I'd like to hear you say "Thanks, Mom. Thanks for %s."`},
			&PromptCard{Prompt: `Just saw this upsetting video! Please retweet!! #stop%s`},
			&PromptCard{Prompt: `Kids, I don't need drugs to get high. I'm high on %s.`},
			&PromptCard{Prompt: `Life for Aboriginal people was forever changed when the white man introduced them to %s.`},
			&PromptCard{Prompt: `Life for American Indians was forever changed when the White Man introduced them to %s.`},
			&PromptCard{Prompt: `Life was difficult for cavemen before %s.`},
			&PromptCard{Prompt: `Lifetime® presents "%s: the Story of %s."`},
			&PromptCard{Prompt: `Lovin’ you is easy ’cause you’re %s.`},
			&PromptCard{Prompt: `Major League Baseball has banned %s for giving players an unfair advantage.`},
			&PromptCard{Prompt: `Make a haiku.`},
			&PromptCard{Prompt: `Mate, do not go in that toilet. There's %s in there.`},
			&PromptCard{Prompt: `Maybe she's born with it. Maybe it's %s.`},
			&PromptCard{Prompt: `Men's Wearhouse: You're gonna like %s. I guarantee it.`},
			&PromptCard{Prompt: `Military historians remember Alexander the Great for his brilliant use of %s against the Persians.`},
			&PromptCard{Prompt: `Money can’t buy me love, but it can buy me %s.`},
			&PromptCard{Prompt: `Mr. and Mrs. Diaz, we called you in because we're concerned about Cynthia. Are you aware that your daughter is %s?`},
			&PromptCard{Prompt: `MTV's new reality show features eight washed-up celebrities living with %s.`},
			&PromptCard{Prompt: `My fellow Americans: Before this decade is out, we will have %s on the moon!`},
			&PromptCard{Prompt: `My mom freaked out when she looked at my browser history and found %s.com/%s.`},
			&PromptCard{Prompt: `My plan for world domination begins with %s.`},
			&PromptCard{Prompt: `Next from J.K. Rowling: Harry Potter and the Chamber of %s.`},
			&PromptCard{Prompt: `Next on ESPN2: The World Series of %s.`},
			&PromptCard{Prompt: `Next up on Channel 4: Ramsay's %s Nightmares.`},
			&PromptCard{Prompt: `Nobody expects the Spanish Inquisition. Our chief weapons are fear, surprise, and %s.`},
			&PromptCard{Prompt: `Now at the Natural History Museum: an interactive exhibit on %s.`},
			&PromptCard{Prompt: `O Canada, we stand on guard for %s.`},
			&PromptCard{Prompt: `Oi! Show us %s!`},
			&PromptCard{Prompt: `Old MacDonald had %s. E-I-E-I-O.`},
			&PromptCard{Prompt: `Only two things in life are certain: death and %s.`},
			&PromptCard{Prompt: `Penalty! %s: that's 5 minutes in the box!`},
			&PromptCard{Prompt: `Qantas now prohibits %s on airplanes.`},
			&PromptCard{Prompt: `Rumor has it that Vladimir Putin's favorite dish is %s stuffed with %s.`},
			&PromptCard{Prompt: `Science will never explain %s.`},
			&PromptCard{Prompt: `Skidamarink a dink a dink, skidamarink a doo, I love %s.`},
			&PromptCard{Prompt: `Sorry everyone, I just %s.`},
			&PromptCard{Prompt: `"Step 1: %s. Step 2: %s. Step 3: Profit."`},
			&PromptCard{Prompt: `Studies show that lab rats navigate mazes 50%% faster after being exposed to %s.`},
			&PromptCard{Prompt: `TFL apologizes for the delay in train service due to %s.`},
			&PromptCard{Prompt: `That's right, I killed %s. How, you ask? %s.`},
			&PromptCard{Prompt: `The blind date was going horribly until we discovered our shared interest in %s.`},
			&PromptCard{Prompt: `The class field trip was completely ruined by %s.`},
			&PromptCard{Prompt: `The Five Stages of Grief: denial, anger, bargaining, %s, acceptance.`},
			&PromptCard{Prompt: `The healing process began when I joined a support group for victims of %s.`},
			&PromptCard{Prompt: `The new Chevy Tahoe. With the power and space to take %s everywhere you go.`},
			&PromptCard{Prompt: `The school excursion was completely ruined by %s.`},
			&PromptCard{Prompt: `The school field trip was completely ruined by %s.`},
			&PromptCard{Prompt: `The school trip was completely ruined by %s.`},
			&PromptCard{Prompt: `The secret to a lasting marriage is communication, communication, and %s.`},
			&PromptCard{Prompt: `The TFL apologizes for the delay in train service due to %s. `},
			&PromptCard{Prompt: `The theme for next year's Eurovision Song Contest is "We are %s."`},
			&PromptCard{Prompt: `The U.S. has begun airdropping %s to the children of Afghanistan.`},
			&PromptCard{Prompt: `They said we were crazy. They said we couldn't put %s inside of %s. They were wrong.`},
			&PromptCard{Prompt: `"This is the way the world ends. Not with a bang but with %s."`},
			&PromptCard{Prompt: `This is your captain speaking. Fasten your seatbelts and prepare for %s.`},
			&PromptCard{Prompt: `This season at the Sydney Opera House, Samuel Beckett's classic existential play: Waiting for %s.`},
			&PromptCard{Prompt: `Today on Jerry Springer: "Help! My son is %s!"`},
			&PromptCard{Prompt: `Tonight's top story: What you don't know about %s could kill you.`},
			&PromptCard{Prompt: `TSA guidelines now prohibit %s on airplanes.`},
			&PromptCard{Prompt: `Turns out that %s-Man was neither the hero we needed nor wanted.`},
			&PromptCard{Prompt: `Uh, hey guys, I know this was my idea, but I'm having serious doubts about %s.`},
			&PromptCard{Prompt: `UKIP: Putting %s First!`},
			&PromptCard{Prompt: `War! What is it good for?`},
			&PromptCard{Prompt: `Well if you'll excuse me, gentlemen, I have a date with %s.`},
			&PromptCard{Prompt: `What am I giving up for Lent?`},
			&PromptCard{Prompt: `What are my parents hiding from me?`},
			&PromptCard{Prompt: `What are school administrators using to curb rampant teenage pregnancy?`},
			&PromptCard{Prompt: `What broke up the original Wiggles?`},
			&PromptCard{Prompt: `What brought the orgy to a grinding halt?`},
			&PromptCard{Prompt: `What did I bring back from Amsterdam?`},
			&PromptCard{Prompt: `What did I bring back from Bali?`},
			&PromptCard{Prompt: `What did I bring back from Mexico?`},
			&PromptCard{Prompt: `What did the US airdrop to the children of Afghanistan?`},
			&PromptCard{Prompt: `What did Vin Diesel eat for dinner?`},
			&PromptCard{Prompt: `What do old people smell like?`},
			&PromptCard{Prompt: `What does Dick Cheney prefer?`},
			&PromptCard{Prompt: `What don't you want to find in your Chinese food?`},
			&PromptCard{Prompt: `What don't you want to find in your doner kebab?`},
			&PromptCard{Prompt: `What don't you want to find in your Kung Pao chicken?`},
			&PromptCard{Prompt: `What don't you want to find in your Mongolian beef?`},
			&PromptCard{Prompt: `What ended my last relationship?`},
			&PromptCard{Prompt: `What gets better with age?`},
			&PromptCard{Prompt: `What gives me uncontrollable gas?`},
			&PromptCard{Prompt: `What has been making life difficult at the nudist colony?`},
			&PromptCard{Prompt: `What helps Barack Obama unwind?`},
			&PromptCard{Prompt: `What helps Obama unwind?`},
			&PromptCard{Prompt: `What is Batman's guilty pleasure?`},
			&PromptCard{Prompt: `What is George W. Bush thinking about right now?`},
			&PromptCard{Prompt: `What kept Margaret Thatcher busy in her waning years?`},
			&PromptCard{Prompt: `What left this stain on my couch?`},
			&PromptCard{Prompt: `What made my first kiss so awkward?`},
			&PromptCard{Prompt: `What makes life worth living?`},
			&PromptCard{Prompt: `What makes me a true blue Aussie?`},
			&PromptCard{Prompt: `What never fails to liven up the party?`},
			&PromptCard{Prompt: `What will always get you laid?`},
			&PromptCard{Prompt: `What will I bring back in time to convince people that I am a powerful wizard?`},
			&PromptCard{Prompt: `What would grandma find disturbing, yet oddly charming?`},
			&PromptCard{Prompt: `What's a girl's best friend?`},
			&PromptCard{Prompt: `What's my anti-drug?`},
			&PromptCard{Prompt: `What's my secret power?`},
			&PromptCard{Prompt: `What's Teach for America using to inspire inner city students to succeed?`},
			&PromptCard{Prompt: `What's that smell?`},
			&PromptCard{Prompt: `What's that sound?`},
			&PromptCard{Prompt: `What's the Canadian government using to inspire rural students to succeed?`},
			&PromptCard{Prompt: `What's the crustiest?`},
			&PromptCard{Prompt: `What's the most emo?`},
			&PromptCard{Prompt: `What's the new fad diet?`},
			&PromptCard{Prompt: `What's the next Happy Meal® toy?`},
			&PromptCard{Prompt: `What's there a ton of in heaven?`},
			&PromptCard{Prompt: `What's there a tonne of in heaven?`},
			&PromptCard{Prompt: `When all else fails, I can always masturbate to %s.`},
			&PromptCard{Prompt: `When I am a billionare, I shall erect a 20-meter (65 foot) statue to commemorate %s.`},
			&PromptCard{Prompt: `When I am President, I will create the Department of %s.`},
			&PromptCard{Prompt: `When I pooped, what came out of my butt?`},
			&PromptCard{Prompt: `When I was tripping on acid, %s turned into %s.`},
			&PromptCard{Prompt: `When I'm in prison, I'll have %s smuggled in.`},
			&PromptCard{Prompt: `When Pharaoh remained unmoved, Moses called down a Plague of %s.`},
			&PromptCard{Prompt: `When you get right down to it, %s is just %s.`},
			&PromptCard{Prompt: `While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on %s.`},
			&PromptCard{Prompt: `White people like %s.`},
			&PromptCard{Prompt: `Who stole the cookies from the cookie jar?`},
			&PromptCard{Prompt: `Why am I sticky?`},
			&PromptCard{Prompt: `Why can't I sleep at night?`},
			&PromptCard{Prompt: `Why do I hurt all over?`},
			&PromptCard{Prompt: `With enough time and pressure, %s will turn into %s.`},
			&PromptCard{Prompt: `Your persistence is admirable, my dear Prince. But you cannot win my heart with %s alone.`},
			&PromptCard{Prompt: `Ain't it nifty? Barb and Bob hit 50! So get off your ass and raise a glass to 50 years of %s.`},
			&PromptCard{Prompt: `Duuuuuuude. You have got to go to space. %s is awesome in space.`},
			&PromptCard{Prompt: `Five, four, three, two, one… %s!`},
			&PromptCard{Prompt: `For hunting in the King's forest, I hereby sentence you to death by %s.`},
			&PromptCard{Prompt: `Give me ten good men and 48 hours. I'll get you %s.`},
			&PromptCard{Prompt: `Goldfinger! / He's the man, / the man with %s.`},
			&PromptCard{Prompt: `Goodbye, %s, hello %s!`},
			&PromptCard{Prompt: `Here's a little something I learned in business school: The customer is always %s.`},
			&PromptCard{Prompt: `Hey, honey. For the bedroom, were you thinking, ""Robin's Egg Blue"" or %sPink?""`},
			&PromptCard{Prompt: `I hate this job. I hate this place. Most of all, I hate %s. I quit.`},
			&PromptCard{Prompt: `I have solved politics. My solution is %s.`},
			&PromptCard{Prompt: `I so drunk I %s.`},
			&PromptCard{Prompt: `I swear to God I'm gonna murder my husband if he doesn't shut the fuck up about %s.`},
			&PromptCard{Prompt: `In bookstores now: "From %s to %s: A memoir."`},
			&PromptCard{Prompt: `In Radiohead's new single, Thom Yorke repeats the phrase "%s" dozens of times over a skittering drum beat.`},
			&PromptCard{Prompt: `It's finally happening! I'm finally doing it! Yes! It's time for %s!`},
			&PromptCard{Prompt: `It's late at night. You're in bed with your lover, Patrick Stewart. He leans over with a twinkle in his eye and asks "How about %s?"`},
			&PromptCard{Prompt: `It's the 21st century. A woman shouldn't have to apologize for %s.`},
			&PromptCard{Prompt: `Ladies and gentlemen, I propose a two-pronged plan. The first prong will be %s, and the second prong will be %s.`},
			&PromptCard{Prompt: `Live from Universal Studios, it's America's favorite game show! "%s or %s?"`},
			&PromptCard{Prompt: `Millions of copies sold! Donald Trump's "The Art of %s."`},
			&PromptCard{Prompt: `New at TGI Fridays! It's what you've been waiting for: The %s Burger.`},
			&PromptCard{Prompt: `Oh no! Here it comes! Ohhhhh god! It's %s.`},
			&PromptCard{Prompt: `Oh you haaaaaaave to see this new documentary on Netflix. I don't want to give anything away, but let's just say it will change the way you look at %s.`},
			&PromptCard{Prompt: `Oh, the weather outside is frightful. But %s is so delightful.`},
			&PromptCard{Prompt: `One, two, three and to the four, Snoop Doggy Dogg and Dr. Dre is %s.`},
			&PromptCard{Prompt: `Personal foul: %s. 15-yard penalty. Automatic first down.`},
			&PromptCard{Prompt: `Rub a dub dub, %s in a tub!`},
			&PromptCard{Prompt: `Say it loud! I'm %s and I'm proud!`},
			&PromptCard{Prompt: `Seriously guys, there's nothing funny about %s.`},
			&PromptCard{Prompt: `Sweetheart, you and your sister escel in different ways. She's got her violin, and you've got %s.`},
			&PromptCard{Prompt: `That's bullshit! They can't fire me for %s!`},
			&PromptCard{Prompt: `The sequel is here! Get Ready for %s2: %s.`},
			&PromptCard{Prompt: `Times have changed, girlfriend. If you want to meet people in New York, you got to be down for %s.`},
			&PromptCard{Prompt: `Unfortunately, no one can be told what %s is. You have to experience it for yourself.`},
			&PromptCard{Prompt: `What has my life become? I'm jerking off to a video called "co-ed absolutely destroyed by %s."`},
			&PromptCard{Prompt: `What sounds great after four margaritas? %s`},
			&PromptCard{Prompt: `What's hot, smelly, and about to die? %s`},
			&PromptCard{Prompt: `What's secretly a Russian plot to destabilize the West? %s`},
			&PromptCard{Prompt: `What's up, YouTube? User DanTheMan wanted to see %s, so here we go.`},
			&PromptCard{Prompt: `Why did the chicken cross the road? %s`},
			&PromptCard{Prompt: `Why my mustache smell so bad? %s`},
			&PromptCard{Prompt: `Yeah that's so hot. I'm so close. Talk about %s again! OH I'M CUMMING!`},
			&PromptCard{Prompt: `You can call me David Copperfield, because I'm about to make %s disappear.`},
			&PromptCard{Prompt: `You city folk would never understand the quiet dignity of %s.`},
		},
		Responses: []ResponseCard{
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
			`%blank`,
		},
	}

	AddPack(pack)
}
